javascript課題③-2 タスク削除機能
takahumi0806/task_management pull request #2
Opened 2020-11-23 07:50 UTC by takahumi0806

javascript課題③-2 タスク削除機能
【要件】
- 削除ボタン押下時にそのタスクを削除できる
- タスク削除時はIDが振り直される
- 削除後、新たにタスクを追加するとIDが連番となっている

削除ボタンを押したら削除される
タスクを削除も連番になるようにしている
再度タスクを追加しても連番となるようになっている

2020-11-24 01:18 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +  <input type="radio" name="" value="1" checked="checked">すべて
nameが不要なら削除しましょう。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +    <div id = 'task_id'>ID</div>
=の前後にはスペースは不要です。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +  function statusidCreate(id){
関数名は動詞+名詞で命名すると良いです。
他の箇所も含めて修正してみましょう。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +    const p_id = document.createElement('p');
jsではキャメルケースでの命名が一般的です。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +    document.getElementById('task_id').appendChild( p_id );
`appendChild( p_id );`ですが、
p_idの前後のスペースは不要です。
```suggestion
    document.getElementById('task_id').appendChild(p_id);
```

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +  function commentCreate(comment,id){
`,`の後ろにはスペースを空けましょう。
他の箇所も同様です。
```suggestion
  function commentCreate(comment, id){
```

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +    parent_id.textContent = "ID"
文字列は`''`で統一しましょう。
jsでは`''`が一般的で、`""`はほぼ使用されません。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +    parent_comment.textContent = "コメント"
todoを削除したときに、parent_idやparent_commentなどのテキストまで消えてしまう設計に違和感を感じます。
今回ですと、todoが表示されるhtmlの部分をtable要素にし、そこに追加していく形にすると、削除するときもtodoを囲っているtrを削除するだけですみますのですっきり記述できるかと思います。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +      tasks.forEach(function(task){
92行目でも全く同じforEachを回していますので、処理がまとめられるかと思います。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +  const button = document.getElementById('task_button');
より具体的な命名ができると良いです。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +  button.addEventListener('click', event => {
引数が使用されていないようですので削除しましょう。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +    tasks.push({id: id,comment: comment ,status: '作業中'})
オブジェクトはkeyとvalueが一致していれば以下のように省略できます。
`{ id }`
これで`{id: id}`と同義で、こちらの記述の方がよく使用されます。
今後この記述ができるような命名の仕方を意識すると更に良いです。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +<script>
この課題から記述量が増えてきますので、jsは別ファイルで記述した方が良いです。

2020-11-24 01:18 UTC, kouki-iwahara commented on index.html
> +  const tasks = []
グローバルな宣言はscriptの上部でまとめて宣言すると可読性が上がります。

2020-11-24 06:32 UTC, takahumi0806 commented on index.html
> +  <input type="radio" name="" value="1" checked="checked">すべて
name削除しました。

2020-11-24 06:36 UTC, takahumi0806 commented on index.html
> +    <div id = 'task_id'>ID</div>
=の前後のスペース削除しました。

2020-11-24 06:55 UTC, takahumi0806 commented on index.html
> +    tasks.push({id: id,comment: comment ,status: '作業中'})
keyとvalueが同じものを変更しました。

2020-11-24 06:59 UTC, takahumi0806 commented on index.html
> +<script>
jsファイルを新規に作成しました。

2020-11-24 07:01 UTC, takahumi0806 commented on index.html
> +  const tasks = []
上部で宣言しました。

2020-11-24 07:01 UTC, takahumi0806 commented on index.html
> +  button.addEventListener('click', event => {
削除しました。

2020-11-24 11:11 UTC, takahumi0806 commented on index.html
> +  function statusidCreate(id){
関数名を動詞+名詞に変更しました。

2020-11-24 11:56 UTC, takahumi0806 commented on index.html
> +    document.getElementById('task_id').appendChild( p_id );
スペース削除しました

2020-11-24 11:57 UTC, takahumi0806 commented on index.html
> +    const p_id = document.createElement('p');
キャメルケースに変更しました。

2020-11-24 12:00 UTC, takahumi0806 commented on index.html
> +  function commentCreate(comment,id){
、の後ろにスペースを開けました。

2020-11-24 12:01 UTC, takahumi0806 commented on index.html
> +    parent_id.textContent = "ID"
シングルコーテーションに変更しました。

2020-11-24 12:02 UTC, takahumi0806 commented on index.html
> +      tasks.forEach(function(task){
関数でまとめました

2020-11-25 10:37 UTC, takahumi0806 commented on index.html
> +  const button = document.getElementById('task_button');
変更しました。

2020-11-25 15:18 UTC, takahumi0806 commented on index.html
> +    parent_comment.textContent = "コメント"
htmlの部分をtable要素にしました。

2020-11-26 21:16 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-11-26 21:16 UTC, kouki-iwahara commented on task.js
> +  const tasks=[]
言葉足らずで申し訳なかったです。
jsでは`=`の前後にはスペースを空けます。
htmlでは不要です。

2020-11-26 21:16 UTC, kouki-iwahara commented on task.js
> +      let taskTable = document.getElementById('targetTable');
constで定義できます。
再代入される場合はlet、されない場合はconstです。
他の箇所も同様に修正しましょう。

2020-11-26 21:16 UTC, kouki-iwahara commented on task.js
> +      let row_num=taskTable.rows.length;
命名はキャメルケースにしましょう。

2020-11-26 21:16 UTC, kouki-iwahara commented on task.js
> +  const createButton=document.getElementById('task_button');
動詞+名詞で宣言すると関数を連想させますので、変数は名詞で宣言しましょう。

2020-11-26 21:16 UTC, kouki-iwahara commented on task.js
> +    newText.textContent = status
文末のセミコロンの有無がバラバラなので、統一しましょう。

2020-11-27 12:59 UTC, takahumi0806 commented on task.js
> +  const tasks=[]
jsの方はスペース開けました。

2020-11-27 13:18 UTC, takahumi0806 commented on task.js
> +      let taskTable = document.getElementById('targetTable');
再代入されない時はconstに変更しました。

2020-11-27 13:20 UTC, takahumi0806 commented on task.js
> +      let row_num=taskTable.rows.length;
キャメルケースにしました。

2020-11-27 13:22 UTC, takahumi0806 commented on task.js
> +  const createButton=document.getElementById('task_button');
変数の宣言を変更しました。

2020-11-27 13:29 UTC, takahumi0806 commented on task.js
> +    newText.textContent = status
文末のセミコロンをつけるように統一しました。

2020-11-28 11:49 UTC, myzktkyk requested changes
動作は問題ありませんでした！
コードについていくつか指摘をしております。

2020-11-28 11:49 UTC, myzktkyk commented on index.html
> +    </tr>
`thead` と `tbody` を使った方がより良いと思います。

```suggestion
    <thead>
      <tr>
        <th>ID</th>
        <th>コメント</th>
        <th>状態</th>
        <th>　　</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
```

2020-11-28 11:49 UTC, myzktkyk commented on task.js
> +      tasks.forEach(function(task) {
アロー関数を使った方が良いかと思いました。

```suggestion
      tasks.forEach((task) => {
```

2020-11-28 11:49 UTC, myzktkyk commented on task.js
> +window.onload = function() {
アロー関数を使った方が良いかと思いました。

```suggestion
window.onload = () => {
```

2020-11-28 11:49 UTC, myzktkyk commented on task.js
> +  function createBtn(newRow, status, id){
`id` が未使用のようです。

```suggestion
  function createBtn(newRow, status) {
```

2020-11-28 12:54 UTC, takahumi0806 commented on task.js
> +  function createBtn(newRow, status, id){
id消しました。

2020-11-28 12:57 UTC, takahumi0806 commented on task.js
> +window.onload = function() {
アロー関数にしました。

2020-11-28 12:58 UTC, takahumi0806 commented on task.js
> +      tasks.forEach(function(task) {
アロー関数にしました。

2020-11-28 16:00 UTC, takahumi0806 commented on index.html
> +    </tr>
thead と tbodyを使用しました。tbodyにアペンドするようにしました。

2020-11-30 01:40 UTC, niganium reviewed
指摘点の修正を確認しました。問題ありません！
以下細かい指摘点です。再提出は不要なので後続の課題までに直しておいてください！

2020-11-30 01:40 UTC, niganium commented on task.js
> +      while(parent.firstChild){
構文上のスペースを設けましょう

2020-11-30 01:40 UTC, niganium commented on task.js
> +          }else{
構文上のスペースを設けましょう

2020-11-30 01:40 UTC, niganium commented on task.js
> +            newId = task.id - 1;
おそらくですがnewIdの変数宣言がどこにも記述されていないように見えます

2020-11-30 02:42 UTC, takahumi0806 commented on task.js
> +            newId = task.id - 1;
宣言しました。

2020-11-30 02:42 UTC, takahumi0806 commented on task.js
> +          }else{
スペースを設けました

2020-11-30 02:43 UTC, takahumi0806 commented on task.js
> +      while(parent.firstChild){
スペースを設けました

2020-11-30 02:43 UTC, merged